name: ErrorLogger
api: 3.0.0
main: vixikhd\errorlogger\ErrorLogger
description: Saves Internal Server Errors
author: VixikHD
version: '1.0'

commands:
  err:
    description: ErrorLogger commands
    permission: errorlogger.cmd

permissions:
  errorlogger.cmd:
    description: Permission for all the ErrorLogger commands
    default: op